### ISSUE TITLE
סמלונים ללייק ולבוסט ולמספר תגובות

### ISSUE THREAD

**Issue by EyalRo** [EyalRo/HebrewPub#14]
אולי משהו דומה ל:

![Screenshot from 2022-11-28 22-05-56](https://user-images.githubusercontent.com/6060053/204451740-9c6157af-f11c-4561-bb92-616ad1b39e71.png)

**Comment by erasta** [comment]
הכנסתי כטקסט בינתיים
צריך לצרוך את font awesome בשביל האייקונים האלו

**Comment by EyalRo** [comment]
כיתוב מספיק טוב לגרסא ראשונית. סוגר
