### ISSUE TITLE
תמיכה באמוג'י מקוסטמים

### ISSUE THREAD

**Issue by EyalRo** [EyalRo/HebrewPub#24]
כרגע לא מציג אמוג'י שאינו סטנדרטי. מאמין שבמידע הפנימי לכל חצרוץ יש את כל הנדרש להציג אמוג'י מקוסטם

**Comment by erasta** [comment]
https://docs.joinmastodon.org/methods/custom_emojis/

**Comment by erasta** [comment]
need to collect what's here for each server (for example toootim) in the beginning and replace each emoji `shortcode` with `url`
https://tooot.im/api/v1/custom_emojis

**Comment by erasta** [comment]
יש אבל חסר עימוד ואנימציה

**Comment by EyalRo** [comment]
יש באג כשיש כמה אמוג'י ברצף
![image](https://user-images.githubusercontent.com/6060053/204960165-44b76273-91d9-4f0d-a438-4530a82a31ed.png)

**Comment by erasta** [comment]
fixed in branch
