### ISSUE TITLE
למשוך חצרוצין במקביל

### ISSUE THREAD

**Issue by EyalRo** [EyalRo/HebrewPub#4]
כרגע המשיכה בלולאה פשוטה

**Comment by erasta** [comment]
זה מתבצע במקביל, שמתי הדפסות בדיבאג אצלי בשביל להדגים:
<img width="321" alt="Screen Shot 2022-12-01 at 10 16 37 PM" src="https://user-images.githubusercontent.com/7118772/205150991-e72fc677-20ec-4c70-90c4-dc06521b419d.png">
